version: '3.8'

services:
  journal:
    build:
      context: './journal'
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - './journal/.env'

  planner:
    build:
      context: './planner'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - './planner/.env'
    environment:
      - NEXT_PUBLIC_JOURNAL_SERVICE_URL=http://journal:3001/graphql
